[tool.poetry]
name = "zadanie3"
version = "0.1.0"
description = ""
authors = ["Grzegorz Piwowarczyk <grzegorz.piwowarczyk@schibsted.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

